### ISSUE TITLE
Multiprocessing on windows

### ISSUE THREAD

**Issue by patrickfuller** [patrickfuller/imolecule#11]
When run on windows, the process fails and spits out a looped error.

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 488, in prepare
Traceback (most recent call last):
  File "<string>", line 1, in <module>
      File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
assert main_name not in sys.modules, main_name
AssertionError: __main__
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
```

From [this stackoverflow](http://stackoverflow.com/questions/26041404/python-windows-and-multiprocessing), it looks like multiprocessing on windows fails when you use relative imports. A weird bug, but an easy fix.

**Comment by patrickfuller** [comment]
To replicate, I opened a new windows 8.1 virtual machine and installed packages.

 * [miniconda](http://conda.pydata.org/miniconda.html) (64-bit, py34)
 * [github/git/powershell](https://windows.github.com/)
 * `conda install pip`, `pip install imolecule`
 * [openbabel GUI](http://openbabel.org/wiki/Category:Installation)
 * **old** openbabel python bindings from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/)

After this mess, I could run with `imolecule`. Everything worked:

![windows](https://cloud.githubusercontent.com/assets/1449833/7013562/f1f86a22-dc7f-11e4-89c1-55cd0b40b4ca.PNG)

I found that windows is hiding the errors of the underlying process, so this reported bug likely had something to do with an improper openbabel install. I also found that windows was not honoring `KeyboardInterrupt` on tornado's server, so I added an explicit try-catch to handle this.

**Comment by patrickfuller** [comment]
Note that the ctrl-c signal takes a couple of seconds on windows. I'm guessing it has something to do with tornado's polling.
